# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0039_auto_20160905_1118'),
        ('rca', '0039_auto_20160906_0934'),
    ]

    operations = [
    ]
