# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0041_auto_20160905_1120'),
        ('rca', '0040_merge'),
    ]

    operations = [
    ]
