# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-06 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0041_auto_20160905_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='ad_username',
            field=models.CharField(blank=True, help_text=b'Username in Active Directory', max_length=255, verbose_name=b'AD username'),
        ),
    ]
