# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0043_merge'),
        ('rca', '0042_staffpage_ad_username'),
    ]

    operations = [
    ]
