# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0044_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudentpage',
            name='ad_username',
            field=models.CharField(blank=True, help_text=b'', max_length=255, verbose_name=b'AD username'),
        ),
    ]
