# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0047_new_contact_page'),
        ('rca', '0047_auto_20161013_1148'),
    ]

    operations = [
    ]
