# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_auto_20160901_1129'),
        ('rca', '0047_new_contact_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsPageProgrammeContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b"You can specify custom text, if you don't want to use a Contact snippet.")),
                ('contact_snippet', models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rca.ContactSnippet')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contactuspage',
            name='contact_form_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_page', to='rca.EnquiryFormPage'),
        ),
        migrations.AddField(
            model_name='contactuspageprogrammecontact',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_contacts', to='rca.ContactUsPage'),
        ),
        migrations.AddField(
            model_name='contactuspageprogrammecontact',
            name='programme',
            field=models.ForeignKey(help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Programme'),
        ),
    ]
