# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [

        ('rca', '0025_auto_20160726_1439'),
        ('rca', '0048_contact_us_page_programme_contact'),
    ]

    operations = [
    ]
