# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0048_merge'),
        ('rca', '0048_contact_us_page_programme_contact'),
    ]

    operations = [
    ]
