# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0049_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmepagecarouselitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programmepagecarouselitem',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='programmepagecarouselitem',
            name='page',
        ),
        migrations.RemoveField(
            model_name='programmepagecarouselitem',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='programmepagefacilitiescarouselitem',
            name='facilities_image',
        ),
        migrations.RemoveField(
            model_name='programmepagefacilitiescarouselitem',
            name='facilities_link',
        ),
        migrations.RemoveField(
            model_name='programmepagefacilitiescarouselitem',
            name='page',
        ),
        migrations.DeleteModel(
            name='ProgrammePageCarouselItem',
        ),
        migrations.DeleteModel(
            name='ProgrammePageFacilitiesCarouselItem',
        ),
    ]
