# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0050_cb835_migrate_renamed_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpage',
            name='featured_content_1',
            field=models.ForeignKey(blank=True, help_text=b'Featured content will be pinned on the page and be shown more prominently', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='featured_content_2',
            field=models.ForeignKey(blank=True, help_text=b'Featured content will be pinned on the page and be shown more prominently', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='featured_content_3',
            field=models.ForeignKey(blank=True, help_text=b'Featured content will be pinned on the page and be shown more prominently', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='featured_content_4',
            field=models.ForeignKey(blank=True, help_text=b'Featured content will be pinned on the page and be shown more prominently', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='featured_content_5',
            field=models.ForeignKey(blank=True, help_text=b'Featured content will be pinned on the page and be shown more prominently', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
