# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0051_auto_20170120_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmepagestudentstory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='programmepagestudentstory',
            name='link',
        ),
        migrations.RemoveField(
            model_name='programmepagestudentstory',
            name='page',
        ),
        migrations.DeleteModel(
            name='ProgrammePageStudentStory',
        ),
    ]
