# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0051_auto_20170127_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightboxgallerypage',
            name='show_on_school_page',
            field=models.BooleanField(default=False, help_text=b''),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='show_on_school_page',
            field=models.BooleanField(default=False, help_text=b''),
        ),
    ]
