# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0052_auto_20170120_1206'),
    ]
