# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0052_auto_20170127_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchitem',
            name='featured',
            field=models.BooleanField(default=False, help_text=b''),
        ),
    ]
