# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-20 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0053_auto_20170120_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmepage',
            name='programme_video',
        ),
        migrations.RemoveField(
            model_name='programmepage',
            name='programme_video_poster_image',
        ),
    ]
