# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0054_auto_20170120_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmepage',
            name='facilities_image',
        ),
        migrations.RemoveField(
            model_name='programmepage',
            name='facilities_link',
        ),
        migrations.RemoveField(
            model_name='programmepage',
            name='facilities_text',
        ),
    ]
