# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0055_auto_20170123_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmepagemanualstafffeed',
            name='page',
        ),
        migrations.RemoveField(
            model_name='programmepagemanualstafffeed',
            name='staff',
        ),
        migrations.DeleteModel(
            name='ProgrammePageManualStaffFeed',
        ),
    ]
