# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('rca', '0057_auto_20170123_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='programme_specification',
            field=models.ForeignKey(blank=True, help_text=b'The link to download the programme specification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
