# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0058_programmepage_programme_specification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammePageHowToApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_text', models.CharField(blank=True, help_text=b'The text for the "How to apply" link', max_length=255)),
                ('link', models.ForeignKey(blank=True, help_text=b'How to apply link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rca.StandardPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_to_apply', to='rca.ProgrammePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
