# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0059_programmepagehowtoapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammePageContactSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact_snippet', models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rca.ContactSnippet')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_snippets', to='rca.ProgrammePage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
