# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0060_programmepagecontactsnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='ma_entry_requirements_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='ma_programme_description_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='ma_programme_description_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventindexrelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='gallerypagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobsindexrelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='pathwaypagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepagecontactsnippet',
            name='contact_snippet',
            field=models.ForeignKey(help_text=b'Choose contact details from the snippet library', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rca.ContactSnippet'),
        ),
        migrations.AlterField(
            model_name='programmepagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='researchinnovationpagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewpagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolpagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardindexrelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
        migrations.AlterField(
            model_name='streampagerelatedlink',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
    ]
