# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0061_auto_20170124_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='ma_entry_requirements_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
    ]
