# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0066_programmepagekeydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='key_content_header',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
    ]
