# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-30 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0068_auto_20170125_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmedocuments',
            name='document',
        ),
        migrations.RemoveField(
            model_name='programmedocuments',
            name='page',
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='facilities_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='facilities_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='graduate_destinations_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='graduate_destinations_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='head_of_programme_statement',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'', null=True, verbose_name=b'Head(s) of programme statement'),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='key_content_header',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='ma_entry_requirements_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='ma_entry_requirements_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='ma_programme_description_link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='ma_programme_description_link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepage',
            name='school',
            field=models.ForeignKey(help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_pages', to='taxonomy.School'),
        ),
        migrations.AlterField(
            model_name='programmepagekeydetails',
            name='text',
            field=models.CharField(blank=True, help_text=b'Key details e.g. number of credits or length of course', max_length=255),
        ),
        migrations.AlterField(
            model_name='programmepageprogramme',
            name='programme',
            field=models.ForeignKey(help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_pages', to='taxonomy.Programme'),
        ),
        migrations.DeleteModel(
            name='ProgrammeDocuments',
        ),
    ]
