# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-31 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0069_auto_20170130_1415'),
        ('rca', '0052_auto_20170127_1312'),
    ]

    operations = [
    ]
