# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0071_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpage',
            name='video_url',
            field=models.URLField(blank=True, help_text=b'', null=True),
        ),
    ]
