# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0070_programmepage_relations'),
        ('rca', '0071_auto_20170206_1004'),
    ]

    operations = [
    ]
