# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0072_schoolpage_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPageContactSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact_snippet', models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rca.ContactSnippet')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_snippets', to='rca.SchoolPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schoolpagecontactemail',
            name='page',
        ),
        migrations.RemoveField(
            model_name='schoolpagecontactphone',
            name='page',
        ),
        migrations.RemoveField(
            model_name='schoolpagecontacttelemail',
            name='page',
        ),
        migrations.DeleteModel(
            name='SchoolPageContactEmail',
        ),
        migrations.DeleteModel(
            name='SchoolPageContactPhone',
        ),
        migrations.DeleteModel(
            name='SchoolPageContactTelEmail',
        ),
    ]
