# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0073_auto_20170208_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepagekeycontent',
            name='link',
            field=models.ForeignKey(help_text=b'Key content link', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
