# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0074_programmepagekeycontent_allow_to_choose_any_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmepagehowtoapply',
            name='link',
            field=models.ForeignKey(help_text=b'How to apply link', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
