# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0075_auto_20170201_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPageResearchLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='head_of_research',
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='head_of_research_link',
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='head_of_research_statement',
        ),
        migrations.AddField(
            model_name='schoolpageresearchlinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_link', to='rca.SchoolPage'),
        ),
        migrations.AddField(
            model_name='schoolpageresearchlinks',
            name='related_page',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
