# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0076_schoolpage_research_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpage',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='contact_link',
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='contact_link_text',
        ),
        migrations.RemoveField(
            model_name='schoolpage',
            name='contact_title',
        ),
    ]
