# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-01 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0077_schoolpage_remove_contact_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpageresearchlinks',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
    ]
