# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def remove_empty_links(apps, schema_editor):
    """
    Having empty links is bad and you should feel bad. Also, I'll delete them.
    """
    SchoolPageFeaturedContent = apps.get_model('rca.SchoolPageFeaturedContent')
    SchoolPageResearchLinks = apps.get_model('rca.SchoolPageResearchLinks')

    for link in SchoolPageResearchLinks.objects.filter(related_page__isnull=True):
        link.delete()

    for content in SchoolPageFeaturedContent.objects.filter(content__isnull=True):
        content.delete()

def do_nothing(apps, schema_editor):
    pass  # Allows us to reverse this migration

class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0078_schoolpageresearchlinks_link_text'),
    ]

    operations = [
        migrations.RunPython(remove_empty_links, do_nothing),
        migrations.AlterField(
            model_name='schoolpagefeaturedcontent',
            name='content',
            field=models.ForeignKey(help_text=b'Featured content will be pinned on the page and be shown more prominently', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='schoolpageresearchlinks',
            name='related_page',
            field=models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
