# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0019_auto_20160901_1129'),
        ('rca', '0079_schoolpage_content_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightBoxGalleryPageRelatedSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_schools', to='rca.LightboxGalleryPage')),
                ('school', models.ForeignKey(help_text=b'', on_delete=django.db.models.deletion.CASCADE, related_name='lightbox_pages', to='taxonomy.School')),
            ],
        ),
    ]
