# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0072_merge'),
        ('rca', '0081_schoolpagealsoofinterest'),
    ]

    operations = [
    ]
