# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0082_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpage',
            name='packery_blog',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of blog items to show'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_events',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of events to show (excluding RCA Talks)'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_events_rcatalks',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of RCA Talk events to show'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_lightbox_galleries',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of lightbox galleries to show'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_news',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of news items to show'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_research',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of research items to show'),
        ),
        migrations.AddField(
            model_name='schoolpage',
            name='packery_standard_pages',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text=b'', null=True, verbose_name=b'Number of standard pages to show'),
        ),
        migrations.AlterField(
            model_name='programmepagefindoutmore',
            name='link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
    ]
