# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-06 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0083_auto_20170206_1047'),
        ('rca', '0083_schoolpage_packery_settings'),
    ]

    operations = [
    ]
