# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0075_programmepagehowtoapply_allow_to_choose_any_page'),
        ('rca', '0083_schoolpage_packery_settings'),
    ]

    operations = [
    ]
