# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-02-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0084_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolpagealsoofinterest',
            old_name='related_page',
            new_name='link',
        ),
        migrations.AlterField(
            model_name='schoolpagealsoofinterest',
            name='link',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='schoolpagealsoofinterest',
            name='link_external',
            field=models.URLField(blank=True, help_text=b'', verbose_name=b'External link'),
        ),
        migrations.AlterField(
            model_name='schoolpagealsoofinterest',
            name='link_text',
            field=models.CharField(blank=True, help_text=b'Link title (or leave blank to use page title)', max_length=255),
        ),
    ]
