# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0086_schoolpageresearchlinks_allow_to_add_external_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleclickCampaignManagerActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(help_text=b'', max_length=255)),
                ('page', models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='double_click', to='wagtailcore.Page')),
            ],
        ),
    ]
