# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-22 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0075_programmepagehowtoapply_allow_to_choose_any_page'),
        ('rca', '0086_schoolpageresearchlinks_allow_to_add_external_links'),
    ]

    operations = [
    ]
