# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-22 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0086_schoolpageresearchlinks_allow_to_add_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationrcaproject',
            name='featured',
            field=models.BooleanField(default=False, help_text=b''),
        ),
    ]
