# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-31 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_areaofexpertise'),
        ('rca', '0086_schoolpageresearchlinks_allow_to_add_external_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPageAreaOfExpertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('area_of_expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='staff.AreaOfExpertise')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='staffpage',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name=b'expert'),
        ),
        migrations.AddField(
            model_name='staffpageareaofexpertise',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_expertise', to='rca.StaffPage'),
        ),
    ]
