# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-26 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0021_auto_20170629_1622'),
        ('rca', '0087_doubleclickcampaignmanageractivities'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudentpage',
            name='mphil_school',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mphil_students', to='taxonomy.School', verbose_name=b'School'),
        ),
        migrations.AddField(
            model_name='newstudentpage',
            name='phd_school',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_students', to='taxonomy.School', verbose_name=b'School'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='mphil_programme',
            field=models.ForeignKey(blank=True, help_text=b'If set, school setting will be ignored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mphil_students', to='taxonomy.Programme', verbose_name=b'Programme'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='phd_programme',
            field=models.ForeignKey(blank=True, help_text=b'If set, school setting will be ignored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phd_students', to='taxonomy.Programme', verbose_name=b'Programme'),
        ),
    ]
