# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-03 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0087_merge'),
        ('rca', '0087_auto_20170503_1428'),
    ]

    operations = [
    ]
