# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 21:26
from __future__ import unicode_literals
import json

from django.db import migrations


def move_area_data(apps, schema_editor):
    """
    Move StaffPage.area to StaffPageRole.area if the user is
    academic/administrative and if StaffPageRole.area is empty.
    """
    StaffPage = apps.get_model('rca', 'StaffPage')

    # Move area data to roles
    records = StaffPage.objects \
                        .prefetch_related('roles') \
                        .filter(staff_type__in=('administrative', 'academic')) \
                        .filter(area__isnull=False)

    print('Found {} records to update.'.format(records.count()))

    for staff in records:
        first_role = staff.roles.filter(area__isnull=True).first()

        # Update revisions
        if staff.has_unpublished_changes:
            # Can't use get_latest_revision() as I am unable to call
            # model methods in migrations.
            revision = staff.revisions.order_by('-created_at', '-id').first()

            if revision:
                revision_json = json.loads(revision.content_json)

                if revision_json['roles']:
                    print('Updating draft of {} (#{}).'.format(staff, staff.pk))

                    revision_json['roles'][0]['area'] = staff.area_id

                    revision.content_json = json.dumps(revision_json)
                    revision.save()

        if first_role is not None:
            print('Updating live version of {} (#{}).'.format(staff, staff.pk))

            first_role.area = staff.area
            first_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ('rca', '0087_doubleclickcampaignmanageractivities'),
        ('taxonomy', '0022_move_area_content_types'),
    ]

    operations = [
        migrations.RunPython(move_area_data)
    ]
