# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-22 13:13
from __future__ import unicode_literals

from django.db import migrations


def populate_innovationrcaproject_featured(apps, schema_editor):
    InnovationRCAProject = apps.get_model('rca.InnovationRCAProject')
    InnovationRCAProject.objects.all().update(featured=True)


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0087_innovationrcaproject_featured'),
    ]

    operations = [
        migrations.RunPython(populate_innovationrcaproject_featured),
    ]
