# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-31 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0087_auto_20170531_1020'),
        ('rca', '0088_merge'),
    ]

    operations = [
    ]
