# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-24 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0089_merge'),
        ('rca', '0087_doubleclickcampaignmanageractivities'),
    ]

    operations = [
    ]
