# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-21 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0089_update_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='head_of_programme_second_title',
            field=models.CharField(blank=True, help_text=b'If you do not specify the title, "Head of Programme" will be used', max_length=255, verbose_name=b"Second head of programme's title"),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='head_of_programme_title',
            field=models.CharField(blank=True, help_text=b'If you do not specify the title, "Head of Programme" will be used', max_length=255, verbose_name=b"Head of programme's title"),
        ),
    ]
