# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0089_staffpage_move_location_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffpage',
            name='staff_location',
        ),
    ]
