# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-26 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0090_merge'),
        ('rca', '0088_student_page_mphil_phd_school'),
    ]

    operations = [
    ]
