# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-10 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0091_merge'),
        ('rca', '0091_staffpage_remove_location'),
    ]

    operations = [
    ]
