# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0091_programmepage_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rca.RcaImage'),
        ),
    ]
