# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0092_programmepage_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmepage',
            name='exclude_from_programme_finder',
            field=models.BooleanField(default=False),
        ),
    ]
