# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-08 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('taxonomy', '0022_degreelevel'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0092_programmepage_poster_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeFinderPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('collapse_upcoming_events', models.BooleanField(default=False, help_text=b'')),
                ('social_text', models.CharField(blank=True, help_text=b'', max_length=255)),
                ('introduction', models.TextField()),
                ('social_image', models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rca.RcaImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ProgrammePageKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='programmepage',
            name='degree_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_programme_pages', to='taxonomy.DegreeLevel'),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='programme_finder_exclude',
            field=models.BooleanField(default=False, help_text=b'Tick to exclude this page from the programme finder.', verbose_name=b'Exclude from programme finder'),
        ),
        migrations.AddField(
            model_name='programmepagekeyword',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='rca.ProgrammePage'),
        ),
        migrations.AddField(
            model_name='programmepagekeyword',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rca_programmepagekeyword_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='programmepage',
            name='programme_finder_keywords',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text=b'A comma-separated list of keywords.', through='rca.ProgrammePageKeyword', to='taggit.Tag', verbose_name=b'Keywords'),
        ),
    ]
