# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-11 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0092_merge'),
        ('rca', '0089_update_help_text'),
    ]

    operations = [
    ]
