# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-11 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0090_head_of_programme_title'),
        ('rca', '0093_merge'),
    ]

    operations = [
    ]
