# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-13 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0094_merge'),
        ('rca', '0091_programmepage_video_embed'),
    ]

    operations = [
    ]
