# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-17 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0095_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'showcase', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'pages', wagtail.wagtailcore.blocks.StreamBlock([(b'Page', wagtail.wagtailcore.blocks.PageChooserBlock())]))]))], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rca.RcaImage'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.TextField(default='', help_text=b"Add asterisks around text to make it appear bold, e.g. 'Make *this* bold.'"),
            preserve_default=False,
        ),
    ]
