# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-04-25 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0092_programmepage_poster_image'),
        ('rca', '0095_merge'),
    ]

    operations = [
    ]
