# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 10:57
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0097_auto_20180919_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([(b'showcase', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'pages', wagtail.wagtailcore.blocks.StreamBlock([(b'Page', wagtail.wagtailcore.blocks.PageChooserBlock())]))], help_text=b'Please choose 5 pages')), (b'video', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'video', wagtail.wagtailembeds.blocks.EmbedBlock()), (b'poster_image', wagtail.wagtailimages.blocks.ImageChooserBlock(required=False))])), (b'testimonials', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'testimonials', wagtail.wagtailcore.blocks.StreamBlock([(b'Testimonial', wagtail.wagtailcore.blocks.StructBlock([(b'image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'quote', wagtail.wagtailcore.blocks.CharBlock()), (b'further_description', wagtail.wagtailcore.blocks.CharBlock(required=False)), (b'reference', wagtail.wagtailcore.blocks.CharBlock(required=False))]))]))])), (b'news', wagtail.wagtailcore.blocks.StructBlock([(b'featured_page', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'more_news_link', wagtail.wagtailcore.blocks.PageChooserBlock())])), (b'events', wagtail.wagtailcore.blocks.StructBlock([(b'more_events_link', wagtail.wagtailcore.blocks.PageChooserBlock())])), (b'two_column_block', wagtail.wagtailcore.blocks.StructBlock([(b'title', wagtail.wagtailcore.blocks.CharBlock()), (b'column_one_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'column_one_link_text', wagtail.wagtailcore.blocks.CharBlock()), (b'column_one_link_page', wagtail.wagtailcore.blocks.PageChooserBlock()), (b'column_two_image', wagtail.wagtailimages.blocks.ImageChooserBlock()), (b'column_two_link_text', wagtail.wagtailcore.blocks.CharBlock()), (b'column_two_link_page', wagtail.wagtailcore.blocks.PageChooserBlock())]))]),
        ),
    ]
