# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-01 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0098_auto_20180921_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='strapline_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name=b'Page'),
        ),
    ]
