# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-24 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0098_auto_20180921_1157'),
        ('rca', '0093_auto_20180808_1231'),
        ('rca', '0096_merge'),
        ('rca', '0094_headersettings'),
    ]

    operations = [
    ]
