# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-17 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0099_merge'),
        ('rca', '0099_auto_20181015_1037'),
    ]

    operations = [
    ]
