# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0100_merge'),
        ('rca', '0100_auto_20181024_1135'),
    ]

    operations = [
    ]
