# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-20 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0100_auto_20181024_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpage',
            name='annual_stripe_plan_id',
            field=models.CharField(blank=True, help_text=b'You need to fill this with the ID from the Stripe website.', max_length=255, verbose_name=b'annual Stripe plan ID'),
        ),
        migrations.AddField(
            model_name='donationpage',
            name='monthly_stripe_plan_id',
            field=models.CharField(blank=True, help_text=b'You need to fill this with the ID from the Stripe website.', max_length=255, verbose_name=b'monthly Stripe plan ID'),
        ),
    ]
