# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-01 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0099_headersettings_strapline_link'),
        ('rca', '0101_merge'),
    ]

    operations = [
    ]
