# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-02-13 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0101_auto_20190213_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='navigation_link_1_page',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='navigation_link_2_page',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='HeaderSettings',
        ),
    ]
