# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-22 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0102_merge'),
        ('rca', '0101_donationpage_stripe_plan_id'),
    ]

    operations = [
    ]
