# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0102_auto_20190213_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpage',
            name='campus',
            field=models.CharField(blank=True, choices=[(b'kensington', b'Kensington'), (b'battersea', b'Battersea'), (b'vauxhall', b'The Workshop, Vauxhall')], help_text=b'', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='mphil_work_location',
            field=models.CharField(blank=True, choices=[(b'kensington', b'Kensington'), (b'battersea', b'Battersea'), (b'vauxhall', b'The Workshop, Vauxhall')], help_text=b'', max_length=255, verbose_name=b'Work location'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='phd_work_location',
            field=models.CharField(blank=True, choices=[(b'kensington', b'Kensington'), (b'battersea', b'Battersea'), (b'vauxhall', b'The Workshop, Vauxhall')], help_text=b'', max_length=255, verbose_name=b'Work location'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='show_work_location',
            field=models.CharField(blank=True, choices=[(b'kensington', b'Kensington'), (b'battersea', b'Battersea'), (b'vauxhall', b'The Workshop, Vauxhall')], help_text=b'', max_length=255, verbose_name=b'Work location'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='show_work_title',
            field=models.CharField(blank=True, help_text=b'The title of your MA Show work/project. Writing and History of Design students should enter their dissertation titles. CCA Students should enter their exhibition title.', max_length=255, verbose_name=b'Dissertation/project title'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='show_work_type',
            field=models.CharField(blank=True, choices=[(b'dissertation', b'Dissertation'), (b'major-project', b'Major project')], help_text=b"Writing and History of Design students should select 'dissertation'. All other students should select 'project'.", max_length=255, verbose_name=b'Work type'),
        ),
    ]
