# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-01-10 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0106_new_student_form_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitem',
            name='area',
            field=models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taxonomy.Area'),
        ),
        migrations.AlterField(
            model_name='eventitem',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'', null=True),
        ),
    ]
