# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-05-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0107_allow_event_blank_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudentpage',
            name='programme_value_override',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
    ]
