# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-12 12:52
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0107_allow_event_blank_body'),
    ]

    run_before = [
        ('shortcourses', '0003_migrate_shortcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='page_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='wagtailcore.Page'),
        ),
    ]
