# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-06-04 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0108_auto_20200604_0924'),
        ('rca', '0108_add_programme_override_field'),
    ]

    operations = [
    ]
