# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-12 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0108_unlink_shortcourse_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
        ),
    ]
