# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-07 12:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0108_auto_20200604_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentpage',
            name='show_work_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'Description of your work or project featured in the show.'),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='statement',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'Brief description of your practice and interests as an artist/designer.'),
        ),
    ]
