# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-07 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0109_remove-student-char-limits'),
        ('rca', '0109_merge'),
    ]

    operations = [
    ]
