# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0109_remove-student-char-limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentpage',
            name='last_name',
            field=models.CharField(blank=True, help_text=b'', max_length=255),
        ),
        migrations.AlterField(
            model_name='newstudentpage',
            name='ma_specialism',
            field=models.CharField(blank=True, help_text=b'', max_length=255, verbose_name=b'Specialism'),
        ),
    ]
