# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-13 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0110_merge'),
        ('rca', '0110_remove_ma_specialism_choices_and_last_name_validation'),
    ]

    operations = [
    ]
