# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-08-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0111_merge'),
        ('rca', '0111_reimplement_ma_specialism_choices'),
    ]

    operations = [
    ]
