# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-11-03 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0111_reimplement_ma_specialism_choices'),
        ('rca', '0109_merge'),
    ]

    operations = [
    ]
