# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2021-02-25 12:02
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rca', '0112_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudentpage',
            name='show_work_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'Description of your work or project featured in the show.', max_length=1200),
        ),
    ]
