SCHOOLS = {
    'Architecture': 'schoolofarchitecture',
    'Interior Design': 'schoolofarchitecture',
    'Animation': 'schoolofcommunication',
    'Information Experience Design': 'schoolofcommunication',
    'Visual Communication': 'schoolofcommunication',
    'Design Interactions': 'schoolofdesign',
    'Design Products': 'schoolofdesign',
    'Global Innovation Design': 'schoolofdesign',
    'Innovation Design Engineering': 'schoolofdesign',
    'Service Design': 'schoolofdesign',
    'Vehicle Design': 'schoolofdesign',
    'Painting': 'schooloffineart',
    'Photography': 'schooloffineart',
    'Printmaking': 'schooloffineart',
    'Sculpture': 'schooloffineart',
    'Critical & Historical Studies': 'schoolofhumanities',
    'Critical Writing In Art & Design': 'schoolofhumanities',
    'Curating Contemporary Art': 'schoolofhumanities',
    'Curating Contemporary Art (College-based)': 'schoolofhumanities',
    u'Curating Contemporary Art (Work\u2013based)': 'schoolofhumanities',
    'Curating Contemporary Art (Work-based)': 'schoolofhumanities',
    'History of Design': 'schoolofhumanities',
    u'RCA/V&A History of Design': 'schoolofhumanities',
    u'RCA/V&A History Of Design': 'historyofdesign',
    u'History of Design V&A/RCA': 'historyofdesign',
    'Ceramics & Glass': 'schoolofmaterial',
    'Goldsmithing, Silversmithing, Metalwork & Jewellery': 'schoolofmaterial',
    'Fashion Menswear': 'schoolofmaterial',
    'Fashion: Menswear': 'schoolofmaterial',
    'Fashion Womenswear': 'schoolofmaterial',
    'Fashion: Womenswear': 'schoolofmaterial',
    'Textiles': 'schoolofmaterial',

    # extras for research items thesis 'department' values
    'Communication Art & Design': 'schoolofcommunication',
    'Communication': 'schoolofcommunication',
    'Ceramics and Glass': 'schoolofmaterial',
    'Critical Historical Studies': 'schoolofhumanities',
    'Critical and Historical Studies': 'schoolofhumanities',
    'Critical Writing In Art and Design': 'schoolofhumanities',
    'Goldsmithing, Silversmithing, Metalwork and Jewellery': 'schoolofmaterial',
    'Industrial Design Engineering': 'schoolofdesign',
    'RCA/ICL Industrial Design Engineering': 'schoolofdesign',
    'GSM&J/History of Design': 'schoolofhumanities',
    'Bartlett School of Graduate Studies': '',
    'Lansdown Centre for Electronic Arts': '',
    'Fashion': 'schoolofmaterial',
    'Conservation': 'schoolofhumanities',
    u'RCA/V&A Conservation': 'schoolofhumanities',
    }

PROGRAMMES = {
    u'Architecture': 'architecture',
    u'Interior Design': 'interiordesign',
    u'Animation': 'animation',
    u'Information Experience Design': 'informationexperiencedesign',
    u'Visual Communication': 'visualcommunication',
    u'Design Interactions': 'designinteractions',
    u'Design Products': 'designproducts',
    u'Global Innovation Design': 'globalinnovationdesign',
    u'Innovation Design Engineering': 'innovationdesignengineering',
    u'Service Design': 'servicedesign',
    u'Vehicle Design': 'vehicledesign',
    u'Painting': 'painting',
    u'Photography': 'photography',
    u'Printmaking': 'printmaking',
    u'Sculpture': 'sculpture',
    u'Critical & Historical Studies': 'criticalhistoricalstudies',
    u'Critical and Historical Studies': 'criticalhistoricalstudies',
    u'Critical Writing In Art & Design': 'criticalwritinginartdesign',
    u'Curating Contemporary Art': 'curatingcontemporaryart',
    u'Curating Contemporary Art (College-based)': 'curatingcontemporaryart',
    u'Curating Contemporary Art (Work-based)': 'curatingcontemporaryart',
    u'Curating Contemporary Art (Work\u2013based)': 'curatingcontemporaryart',
    u'History of Design': 'historyofdesign',
    u'RCA/V&A History of Design': 'historyofdesign',
    u'RCA/V&A History Of Design': 'historyofdesign',
    u'History of Design V&A/RCA': 'historyofdesign',
    u'Ceramics & Glass': 'ceramicsglass',
    u'Goldsmithing, Silversmithing, Metalwork & Jewellery': 'goldsmithingsilversmithingmetalworkjewellery',
    u'Fashion Menswear': 'fashionmenswear',
    u'Fashion: Menswear': 'fashionmenswear',
    u'Fashion Womenswear': 'fashionwomenswear',
    u'Fashion: Womenswear': 'fashionwomenswear',
    u'Textiles': 'textiles',
    u'Industrial Design Engineering': 'industrialdesignengineering',
    u'RCA/ICL Industrial Design Engineering': 'industrialdesignengineering',
    u'Service Design': 'servicedesign',
    u'Conservation': 'conservation',
    u'RCA/V&A Conservation': 'conservation',
    u'Communication Art & Design': 'communicationartdesign',

    # extras for staff page
    'School of Humanities': 'schoolofhumanities',
}

DEGREE_SUBJECTS = {
    'Animation': 'animation',
    'Architecture': 'architecture',
    'Ceramics & Glass': 'ceramicsglass',
    'Curating Contemporary Art (College-based)': 'curatingcontemporaryart',
    'Curating Contemporary Art': 'curatingcontemporaryart',
    u'Curating Contemporary Art (Work\u2013based)': 'curatingcontemporaryart',
    'Curating Contemporary Art (Work-based)': 'curatingcontemporaryart',
    'Critical & Historical Studies': 'criticalhistoricalstudies',
    u'Critical and Historical Studies': 'criticalhistoricalstudies',
    'Critical Writing In Art & Design': 'criticalwritinginartdesign',
    'Design Interactions': 'designinteractions',
    'Design Products': 'designproducts',
    'Fashion Menswear': 'fashionmenswear',
    'Fashion: Menswear': 'fashionmenswear',
    'Fashion Womenswear': 'fashionwomenswear',
    'Fashion: Womenswear': 'fashionwomenswear',
    'Innovation Design Engineering': 'innovationdesignengineering',
    'History of Design': 'historyofdesign',
    u'RCA/V&A History of Design': 'historyofdesign',
    u'RCA/V&A History Of Design': 'historyofdesign',
    u'History of Design V&A/RCA': 'historyofdesign',
    'Painting': 'painting',
    'Photography': 'photography',
    'Printmaking': 'printmaking',
    'Sculpture': 'sculpture',
    'Goldsmithing, Silversmithing, Metalwork & Jewellery': 'goldsmithingsilversmithingmetalworkjewellery',
    'Textiles': 'textiles',
    'Printed Textiles': 'textiles',
    'Constructed Textiles': 'textiles',
    'Vehicle Design': 'vehicledesign',
    'Visual Communication': 'visualcommunication',
    u'Industrial Design Engineering': 'industrialdesignengineering',
    u'RCA/ICL Industrial Design Engineering': 'industrialdesignengineering',
    u'Service Design': 'servicedesign',
    u'Conservation': 'conservation',
    u'RCA/V&A Conservation': 'conservation',
    u'Communication Art & Design': 'communicationartdesign',
}

PROGRAMME_SPECIALISMS = {
        'Printed Textiles': ('Textiles', 'Printed Textiles'),
        'Constructed Textiles': ('Textiles', 'Constructed Textiles'),
        }
