# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcoursepage',
            name='page_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='wagtailcore.Page'),
        ),
    ]
