# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-05 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0107_allow_event_blank_body'),
        ('shortcourses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCourseEnquiryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('social_text', models.CharField(blank=True, help_text=b'', max_length=255)),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'This text will precede the Access Planit enquiry form.')),
                ('social_image', models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rca.RcaImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ShortCourseEnquiryRelatedShortCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shortcoursepage',
            name='ap_course_id',
            field=models.CharField(blank=True, help_text=b'Course ID from the Access Planit booking system. This allows the inclusion of booking and enquiry links.', max_length=8),
        ),
        migrations.AddField(
            model_name='shortcourseenquiryrelatedshortcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shortcourses.ShortCoursePage'),
        ),
        migrations.AddField(
            model_name='shortcourseenquiryrelatedshortcourse',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcourses', to='shortcourses.ShortCourseEnquiryPage'),
        ),
    ]
