# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('rca', '0107_allow_event_blank_body'),
        ('shortcourses', '0002_add_shortcourse_enquiry_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortCourseBookingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('social_text', models.CharField(blank=True, help_text=b'', max_length=255)),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True, help_text=b'This text will precede the Access Planit enquiry form.')),
                ('social_image', models.ForeignKey(blank=True, help_text=b'', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rca.RcaImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AddField(
            model_name='shortcoursepage',
            name='booking_disabled_text',
            field=models.CharField(blank=True, help_text=b'If booking is not enabled, this text will be shown instead.', max_length=255),
        ),
        migrations.AddField(
            model_name='shortcoursepage',
            name='booking_enabled',
            field=models.BooleanField(default=True, help_text=b'If checked, a link will be shown to book using Access Planit.'),
        ),
        migrations.AddField(
            model_name='shortcoursepage',
            name='details',
            field=wagtail.wagtailcore.fields.RichTextField(help_text=b'Course details such as dates, duration, location and fee. Booking and enquiry links will be appended to this.', null=True),
        ),
    ]
