# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-12 12:55
from __future__ import unicode_literals

from django.db import migrations

STANDARDPAGE_COURSE_IDS = [13240, 13243, 17627, 17589]
TAXONOMY_DEGREE_LEVEL = 5
TAXONOMY_SCHOOL_ID = 59


def migrate_to_shortcourse(apps, schema_editor):
    ShortCoursePage = apps.get_model('shortcourses.ShortCoursePage')
    ContentType = apps.get_model('contenttypes.ContentType')
    DegreeLevel = apps.get_model('taxonomy.DegreeLevel')
    School = apps.get_model('taxonomy.School')
    degree_level = DegreeLevel.objects.get(pk=TAXONOMY_DEGREE_LEVEL)
    school_id = School.objects.get(pk=TAXONOMY_SCHOOL_ID)

    # Get content type for short course page model
    shortcourse_content_type, created = ContentType.objects.get_or_create(
        model='shortcoursepage', app_label='shortcourses')

    # Migrate section pages
    StandardPage = apps.get_model('rca.StandardPage')
    standardpage_coursepages = StandardPage.objects.filter(
        pk__in=STANDARDPAGE_COURSE_IDS
    )
    for standard_page in standardpage_coursepages:
        page = standard_page.page_ptr
        page.content_type = shortcourse_content_type
        page.save(update_fields=['content_type'])

        ShortCoursePage.objects.create(
            page_ptr_id=standard_page.page_ptr_id,
            ## Short course fields
            details=' ',
            booking_enabled=True,
            booking_disabled_text='',
            programme_finder_exclude=False,
            ap_course_id='',
            degree_level=degree_level,
            related_school=school_id,
            ## Shared fields
            # body=p.body,
            # collapse_upcoming_events=p.collapse_upcoming_events,
            # expire_at=p.expire_at,
            # expired=p.expired,
            # feed_image=p.feed_image,
            # first_published_at=p.first_published_at,
            # go_live_at=p.go_live_at,
            # intro=p.intro,
            # latest_revision_created_at=p.latest_revision_created_at,
            # live=p.live,
            # locked=p.locked,
            # middle_column_body=p.middle_column_body,
            # numchild=p.numchild,
            # owner=p.owner,
            # related_area=p.related_area,
            # related_programme=p.related_programme,
            # search_description=p.search_description,
            # seo_title=p.seo_title,
            # show_in_menus=p.show_in_menus,
            # show_on_homepage=p.show_on_homepage,
            # show_on_school_page=p.show_on_school_page,
            # slug=slug,
            # social_image=p.social_image,
            # social_text=p.social_text,
            # strapline=p.strapline,
            # tags=p.tags,
            # title=p.title,
            # twitter_feed=p.twitter_feed,
        )

        standard_page.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourses', '0002_unlink_shortcourse_pages'),
    ]

    operations = [
        migrations.RunPython(migrate_to_shortcourse, migrations.RunPython.noop),
    ]
