# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-02-06 09:39
from __future__ import unicode_literals

import logging

from django.db import migrations

logger = logging.getLogger('shortcourses')


def create_booking_enquiry_pages(apps, schema_editor):

    StandardIndex = apps.get_model('rca', 'StandardIndex')

    EnquiryPage = apps.get_model('shortcourses', 'ShortCourseEnquiryPage')
    BookingPage = apps.get_model('shortcourses', 'ShortCourseBookingPage')

    short_courses_index = StandardIndex.objects.filter(title="Short Courses")

    if short_courses_index:
        register_your_interest = EnquiryPage()
        register_your_interest.title = "Register your interest"
        short_courses_index.add_child(instance=register_your_interest)
        register_your_interest.save()

        book_course = BookingPage()
        book_course.title = "Book a course"
        short_courses_index.add_child(instance=book_course)
        book_course.save()
        logger.info("Enquiry and booking form pages have been created.")
    else:
        logger.warning(
            "Enquiry and booking form pages were not created because \
            'Short Courses' index page could not be found.")


class Migration(migrations.Migration):

    dependencies = [
        ('shortcourses', '0003_add_shortcourse_booking_link'),
    ]

    operations = [
        migrations.RunPython(create_booking_enquiry_pages,
                             migrations.RunPython.noop)
    ]
