# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-05-03 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rca_show', '0008_showindexpage_hide_animation_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showexhibitionmappage',
            name='campus',
            field=models.CharField(blank=True, choices=[(b'kensington', b'Kensington'), (b'battersea', b'Battersea'), (b'vauxhall', b'The Workshop, Vauxhall')], max_length=255, null=True),
        ),
    ]
