# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-29 15:22
from __future__ import unicode_literals

from django.db import migrations


def remove_school_of_material(apps, schema_editor):
    School = apps.get_model('taxonomy.School')
    Programme = apps.get_model('taxonomy.Programme')

    Programme.objects\
        .filter(slug__in=['mres-material', 'goldsmithingsilversmithingmetalworkjewellery'])\
        .update(school=School.objects.get(slug='school-of-arts-and-humanities'), disabled=True)

    assert School.objects.filter(slug='schoolofmaterial').delete()[0] == 1


def do_nothing(apps, schema_editor):
    pass  # Allows us to reverse this migration


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0020_6_to_4_schools'),
    ]

    operations = [
        migrations.RunPython(remove_school_of_material, do_nothing),
    ]
