# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-15 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0022_move_area_content_types'),
        ('taxonomy', '0022_degreelevel'),
    ]

    operations = [
    ]
