HELP_TEXT = {
    ('rca.RelatedLinkMixin', 'link_text'): 'Link title (or leave blank to use page title',
    ('rca.Advert', 'text'): 'bold text',
    ('rca.CustomContentModuleBlock', 'image'): 'The image for the module block',
    ('rca.ContactSnippet', 'title'): 'This is the reference name for the contact. This is not displayed on the frontend.',
    ('rca.ContactSnippet', 'contact_title'): 'This is the optional title, displayed on the frontend',
    ('rca.SchoolPage', 'background_image'): 'The full bleed image in the background',
    ('rca.SchoolPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.SchoolPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ProgrammePage', 'background_image'): 'The full bleed image in the background',
    ('rca.ProgrammePage', 'head_of_programme'): 'Select the profile page of the Head of this programme.',
    ('rca.ProgrammePage', 'head_of_programme_link'): 'The link to the Head of Programme Welcome Page',
    ('rca.ProgrammePage', 'programme_video'): "The web addres for the programme video on Vimeo. For example, 'http://vimeo.com/62715625'.",
    ('rca.ProgrammePage', 'programme_video_poster_image'): 'The poster image for the programme video',
    ('rca.ProgrammePage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.ProgrammePage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle, hashtag or search term',
    ('rca.ProgrammePage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.NewsIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.NewsIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.NewsItem', 'listing_intro'): 'Used only on pages listing news items',
    ('rca.NewsItem', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.PressReleaseIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.PressReleaseIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.PressRelease', 'listing_intro'): 'Used only on pages listing news items',
    ('rca.PressRelease', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.EventItemDatesTimes', 'date_to'): 'Not required if event is on a single day',
    ('rca.EventItemDatesTimes', 'time_other'): 'Use this field to give additional information about start and end times',
    ('rca.EventItem', 'specific_directions'): 'Brief, more specific location e.g Go to reception on 2nd floor',
    ('rca.EventItem', 'special_event'): 'Toggling this is a quick way to remove/add an event from signage without deleting the screens defined below',
    ('rca.EventItem', 'eventbrite_id'): 'Must be a ten-digit number. You can find for you event ID by logging on to Eventbrite, then going to the Manage page for your event. Once on the Manage page, look in the address bar of your browser for eclass=XXXXXXXXXX. This ten-digit number after eclass= is the event ID.',
    ('rca.EventItem', 'listing_intro'): 'Used only on pages listing event items',
    ('rca.EventItem', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.EventIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.EventIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.TalksIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle, hashtag or search term',
    ('rca.TalksIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ReviewsIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle, hashtag or search term',
    ('rca.ReviewsIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ReviewPage', 'listing_intro'): 'Used only on pages listing jobs',
    ('rca.ReviewPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.StandardPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.StandardPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.StandardPage', 'tags'): 'Use the "student-story" or "alumni-story" tags to make this page appear in the homepage packery (if "Show on homepage" is ticked too).',
    ('rca.StandardIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.StandardIndex', 'background_image'): 'The full bleed image in the background',
    ('rca.StandardIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.HomePage', 'background_image'): 'The full bleed image in the background',
    ('rca.HomePage', 'packery_student_work'): 'Student pages flagged to Show On Homepage must have at least one carousel item',
    ('rca.HomePage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.HomePage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.JobPage', 'listing_intro'): 'Used only on pages listing jobs',
    ('rca.JobPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.JobsIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.JobsIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.AlumniIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.AlumniPage', 'listing_intro'): 'Used only on pages displaying a list of pages of this type',
    ('rca.AlumniPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.StaffPage', 'school'): 'Please complete this field for academic and administrative staff only',
    ('rca.StaffPage', 'staff_location'): 'Please complete this field for technical staff only',
    ('rca.StaffPage', 'listing_intro'): 'Used only on pages displaying a list of pages of this type',
    ('rca.StaffPage', 'supervised_student_other'): "Enter names of research students here who don't have a student profile. Supervised students with profile pages are pulled in automatically.",
    ('rca.StaffPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.StaffIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.StaffIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ResearchStudentIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle, hashtag or search term',
    ('rca.ResearchStudentIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.NewStudentPagePreviousDegree', 'degree'): 'Include degree level, subject, institution name and year of graduation, separated by commas e.g. BA Fine Art, University of Brighton, 2011',
    ('rca.NewStudentPageExhibition', 'exhibition'): 'Include exhibition title, gallery, city and year, separated by commas',
    ('rca.NewStudentPageExperience', 'experience'): 'Include job title, company name, city and year(s), separated by commas',
    ('rca.NewStudentPageContactsEmail', 'email'): 'You can use your personal email as well as firstname.surname@network.rca.ac.uk',
    ('rca.NewStudentPageContactsPhone', 'phone'): 'UK mobile e.g. 07XXX XXXXXX or overseas landline, e.g. +33 (1) XXXXXXX',
    ('rca.NewStudentPagePublication', 'name'): 'Include author (if not you), article title, joutnal title, issue number, year, pages, separated by commas',
    ('rca.NewStudentPageConference', 'name'): 'Include paper title, conference, institution, date, separated by commas',
    ('rca.NewStudentPageAward', 'award'): 'Include prize, award title and year, separated by commas',
    ('rca.NewStudentPageShowCollaborator', 'name'): "Include collaborator's name and programme (if RCA), separated by commas",
    ('rca.NewStudentPageShowSponsor', 'name'): 'List companies and individuals that have provided financial or in kind sponsorship for your final project, separated by commas',
    ('rca.NewStudentPageMPhilCollaborator', 'name'): "Include collaborator's name and programme (if RCA), separated by commas",
    ('rca.NewStudentPageMPhilSponsor', 'name'): 'List companies and individuals that have provided financial or in kind sponsorship for your final project, separated by commas',
    ('rca.NewStudentPageMPhilSupervisor', 'supervisor'): "Search for your RCA supervisor's staff page ",
    ('rca.NewStudentPageMPhilSupervisor', 'supervisor_other'): 'Any external supervisors, or RCA supervisors without a staff page',
    ('rca.NewStudentPagePhDCollaborator', 'name'): "Include collaborator's name and programme (if RCA), separated by commas",
    ('rca.NewStudentPagePhDSponsor', 'name'): 'List companies and individuals that have provided financial or in kind sponsorship for your final project, separated by commas',
    ('rca.NewStudentPagePhDSupervisor', 'supervisor'): "Search for your RCA supervisor's staff page ",
    ('rca.NewStudentPagePhDSupervisor', 'supervisor_other'): 'Any external supervisors, or RCA supervisors without a staff page',
    ('rca.NewStudentPage', 'profile_image'): 'Self-portrait image, square, 500x500 pixels',
    ('rca.NewStudentPage', 'statement'): 'Brief description of your practice and interests as an artist/designer',
    ('rca.NewStudentPage', 'twitter_handle'): 'Twitter handle without the @ symbol',
    ('rca.NewStudentPage', 'funding'): 'Include scholarships or major funding bodies, including research councils',
    ('rca.NewStudentPage', 'feed_image'): 'This image displays in content feeds, such as the news carousel. Should be 16:9 aspect ratio.',
    ('rca.NewStudentPage', 'innovation_rca_fellow'): 'Tick this box only if you are currently an InnovationRCA Fellow',
    ('rca.NewStudentPage', 'postcard_image'): "Image will be used to print a set of postcards with your contact details, for you to use during the show. The image will not appear in your Show online catalogue. Image must be A6 plus 2mm 'bleed' on each edge (152 x 109mm or 1795 x 1287px @ 300 dpi).  This must be uploaded at the correct size and before the deadline for postcards to be printed.",
    ('rca.NewStudentPage', 'ma_specialism'): 'Only complete for Fashion (Knitwear; Accessories, Footwear and Millinery) Textiles (Knit; Mixed-media; Print, Weave) or Fine Art (Performance; Moving Image)',
    ('rca.NewStudentPage', 'ma_in_show'): "Tick for MA students in this year's Show ",
    ('rca.NewStudentPage', 'show_work_title'): 'The title of your MA Show work/project. CWA&D and History of Design students should enter their dissertation titles. CCA Students should enter their exhibition title.',
    ('rca.NewStudentPage', 'show_work_type'): "CWA&D and History of Design students should select 'dissertation'. All other students should select 'project'.",
    ('rca.NewStudentPage', 'show_work_description'): 'Description of your work or project featured in the show',
    ('rca.NewStudentPage', 'mphil_start_year'): 'The year you began your MPhil',
    ('rca.NewStudentPage', 'mphil_statement'): 'Description of your MPhil dissertation or project',
    ('rca.NewStudentPage', 'mphil_in_show'): "Please tick only if you're an MPhil in the Show this year",
    ('rca.NewStudentPage', 'phd_start_year'): 'The year you began your PhD',
    ('rca.NewStudentPage', 'phd_statement'): 'Description of your PhD dissertation or project',
    ('rca.NewStudentPage', 'phd_in_show'): 'Please tick only if you are a PhD student in the Show this year',
    ('rca.RcaNowPage', 'body'): "This is the main text of your post. It should be a description the work, project or idea you're posting about",
    ('rca.RcaNowPage', 'author'): "Enter your full name as you'd like it to appear, e.g. Tom Smith",
    ('rca.RcaNowPage', 'date'): 'The date of your RCA Now post',
    ('rca.RcaNowPage', 'area'): "Select an area of the College only if it's relevant to your post",
    ('rca.RcaNowPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.RcaNowPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.RcaNowIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.RcaBlogPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.RcaBlogPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.RcaBlogIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.RcaBlogIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ResearchItemCreator', 'person'): "Choose an existing person's page, or enter a name manually below (which will not be linked).",
    ('rca.ResearchItemCreator', 'manual_person_name'): 'Only required if the creator has no page of their own to link to',
    ('rca.ResearchItem', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.ResearchItem', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ResearchInnovationPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.ResearchInnovationPage', 'background_image'): 'The full bleed image in the background',
    ('rca.ResearchInnovationPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.CurrentResearchPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.CurrentResearchPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.GalleryPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.GalleryPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ContactUsPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.DonationPage', 'payment_description'): 'This value will be stored along with each donation made on this page to help ditinguish them from donations on other pages.',
    ('rca.DonationPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.InnovationRCAProjectCreator', 'person'): "Choose an existing person's page, or enter a name manually below (which will not be linked).",
    ('rca.InnovationRCAProjectCreator', 'manual_person_name'): 'Only required if the creator has no page of their own to link to',
    ('rca.InnovationRCAProject', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.InnovationRCAProject', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.InnovationRCAIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.InnovationRCAIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ReachOutRCAWorkshopLeader', 'person'): "Choose an existing person's page, or enter a name manually below (which will not be linked).",
    ('rca.ReachOutRCAWorkshopLeader', 'person'): 'Only required if the creator has no page of their own to link to',
    ('rca.ReachOutRCAWorkshopAssistant', 'person'): "Choose an existing person's page, or enter a name manually below (which will not be linked).",
    ('rca.ReachOutRCAWorkshopAssistant', 'person'): 'Only required if the creator has no page of their own to link to',
    ('rca.ReachOutRCAProject', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.ReachOutRCAProject', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.ReachOutRCAIndex', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.ReachOutRCAIndex', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
    ('rca.StreamPage', 'twitter_feed'): 'Replace the default Twitter feed by providing an alternative Twitter handle (without the @ symbol)',
    ('rca.StreamPage', 'feed_image'): 'The image displayed in content feeds, such as the news carousel. Should be 16:9 ratio.',
}


ALL_FIELDS = []


def help_text(model_name, field_name, default=''):
    # Commented out to improve memory usage. Uncomment if you would like
    # to export the fields to CSV
    # ALL_FIELDS.append((model_name, field_name, default))

    if (model_name, field_name) in HELP_TEXT:
        return HELP_TEXT[model_name, field_name]
    else:
        return default


def export_csv(f):
    from django.db.models import get_model
    import csv

    csvwriter = csv.writer(f)
    for model_name, field_name, help_text in ALL_FIELDS:
        model = get_model(*model_name.split('.'))

        if model is not None:
            field_verbose_name = model._meta.get_field_by_name(field_name)[0].verbose_name.title()
        else:
            field_verbose_name = field_name.replace('_', ' ').title()

        csvwriter.writerow([model_name, field_name, field_verbose_name, help_text])
