REACHOUT_PROJECT_CHOICES = (
    ('aperfectplacetogrow', 'A Perfect Place to Grow'),
    ('artontheunderground', 'Art on the Underground'),
    ('thebigdraw', 'The Big Draw'),
    ('creativequarter', 'Creative Quarter'),
    ('designcamp', 'Design Camp'),
    ('designingthefuture', 'Designing the Future'),
    ('durhamwharfresidency', 'Durham Wharf Residency'),
    ('friezeartfair', 'Frieze Art Fair'),
    ('helenhamlynexhibitionworkshops', 'Helen Hamlyn Exhibition workshops'),
    ('makeyourownmyths', 'Make Your Own Myths'),
    ('mangroupdrawingprizeworkshops', 'Man Group Drawing Prize workshops'),
    ('openspace', 'Open Space'),
    ('rcablack', 'RCABlack'),
    ('rcasecret', 'RCASecret'),
    ('revival', 'Revival'),
    ('showrca', 'Show RCA'),
    ('teachersstudio', "Teachers' Studio"),
    ('workinprogressshow', 'Work-in-progress Show'),
)

REACHOUT_PARTICIPANTS_CHOICES = (
    ('alexandraandainsworthestate', 'Alexandra and Ainsworth Estate'),
    ('archbishoptenisonsschool', 'Archbishop Tenison\'s School'),
    ('ashcrofttechnologyacademy', 'Ashcroft Technology Academy'),
    ('bexhillcollege', 'Bexhill College'),
    ('bishopdouglassschool', 'Bishop Douglass School'),
    ('blackheathbluecoat', 'Blackheath Bluecoat'),
    ('blanchenevileschool', 'Blanche Nevile School'),
    ('bournemouthpoolefecollege', 'Bournemouth & Poole FE College'),
    ('brentsidehighschool', 'Brentside High School'),
    ('bsixcollege', 'BSix College'),
    ('burntwoodschool', 'Burntwood School'),
    ('centralstmartins', 'Central St Martins'),
    ('cityandislington college', 'City and Islington College'),
    ('cityoflondonschool', 'City of London School'),
    ('claptongirlsacademy', "Clapton Girls' Academy"),
    ('cumberlandschool', 'Cumberland School'),
    ('downtonlacemakers', "Downton lace-makers"),
    ('dunravenschool', 'Dunraven School'),
    ('elmgreenschool', 'Elmgreen School'),
    ('elthamhillschool', 'Eltham Hill School'),
    ('erithschool', 'Erith School'),
    ('ernestbevincollege', 'Ernest Bevin College'),
    ('families', 'Families'),
    ('foresthillschool', 'Forest Hill School'),
    ('fulhamcrossgirlsschool', "Fulham Cross Girls' School"),
    ('greycoathospitalschool', 'Grey Coat Hospital School'),
    ('greycourtschool', 'Grey Court School'),
    ('griffinprimaryschool', 'Griffin Primary School'),
    ('hasmoneanhighschool', 'Hasmonean High School'),
    ('haveringcollege', 'Havering College'),
    ('haveringsixthformcollege', 'Havering Sixth Form College'),
    ('haverstockschool', 'Haverstock School'),
    ('heathfieldschoolforgirls', 'Heathfield School for Girls'),
    ('hendonschool', 'Hendon School'),
    ('henriettabarnettschool', "Henrietta Barnett School"),
    ('henryfawcettprimaryschool', 'Henry Fawcett Primary School'),
    ('highburygroveschool', "Highbury Grove School"),
    ('hollandparkschool', 'Holland Park School'),
    ('horizonscentre', "Horizons Centre"),
    ('intouniversity', 'IntoUniversity'),
    ('islingtonartsandmediaschool', "Islington Arts and Media School"),
    ('kingsburyhighschool', 'Kingsbury High School'),
    ('lewishamsouthwarkcollege', 'Lewisham Southwark College'),
    ('newhavenschool', 'Newhaven School'),
    ('newmancatholiccollege', 'Newman Catholic College'),
    ('northolthighschool', 'Northolt High School'),
    ('oaklandsschool', 'Oaklands School'),
    ('outsetfamily', 'Outset Family'),
    ('parkhighschool', 'Park High School'),
    ('parkviewacademy', 'Park View Academy'),
    ('pimlicoacademy', 'Pimlico Academy'),
    ('queensparkcommunityschool', 'Queens Park Community School'),
    ('ravensbourne', 'Ravensbourne'),
    ('rcastudents', "RCA students"),
    ('refugeesandasylumseekers', 'Refugees and asylum seekers'),
    ('residentsofstmarynewingtonclose', 'Residents of St Mary Newington Close'),
    ('ripongrammarschool', "Ripon Grammar School"),
    ('salesiancollege', 'Salesian College'),
    ('salisburymuseum', 'Salisbury Museum'),
    ('sirgeorgemonouxsixthformcollege', 'Sir George Monoux Sixth Form College'),
    ('southendhighschoolforboys', "Southend High School for Boys"),
    ('southwarkpensionerscentre', "Southwark Pensioners' Centre"),
    ('staugustinescofeschool', "St Augustine's C of E School"),
    ('stceciliasschool', "St Cecilia's School"),
    ('stcharlescatholicsixthformcollege', 'St Charles Catholic Sixth Form College'),
    ('stjamescatholichighschool', "St James' Catholic High School"),
    ('stmaryleboneschoolcofeschool', "St Marylebone School C of E School"),
    ('stmichaelscatholicgrammarschool', "St Michael's Catholic Grammar School"),
    ('surreysquareprimaryschool', "Surrey Square Primary School"),
    ('teachers', 'Teachers'),
    ('thecomptonschool', "The Compton School"),
    ('thelaurels', 'The Laurels'),
    ('ucaepsom', 'UCA Epsom'),
    ('villiershighschool', "Villiers High School"),
    ('westlondoncollege', 'West London College'),
    ('westminsteracademy', "Westminster Academy"),
    ('westthamescollege', 'West Thames College'),
    ('whitefieldschool', "Whitefield School"),
    ('williamellisschool', "William Ellis School"),
    ('woolwichpolytechnicschool', "Woolwich Polytechnic School"),
    ('wrenacademy', "Wren Academy"),
    ('youngcarers', "Young Carers"),
)

REACHOUT_THEMES_CHOICES = (
    ('animation','Animation'),
    ('architecture','Architecture'),
    ('ceramicsglass','Ceramics & Glass'),
    ('collaboration','Collaboration'),
    ('collage','Collage'),
    ('curating','Curating'),
    ('drawing','Drawing'),
    ('fashion','Fashion'),
    ('film','Film'),
    ('graphicdesign','Graphic Design'),
    ('jewellery','Jewellery'),
    ('illustration','Illustration'),
    ('information design','Information Design'),
    ('innovation','Innovation'),
    ('lifedrawing','Life Drawing'),
    ('painting','Painting'),
    ('performance','Performance'),
    ('photography','Photography'),
    ('printmaking','Printmaking'),
    ('productdesign','Product Design'),
    ('sculpture','Sculpture'),
    ('textiles','Textiles'),
    ('vehicledesign','Vehicle Design'),
    ('visualcommunication','Visual Communication'),
    ('writing','Writing'),
)

REACHOUT_PARTNERSHIPS_CHOICES = (
    ('artontheunderground', 'Art on the Underground'),
    ('creativequarter', 'Creative Quarter'),
    ('burberryfoundation', 'Burberry Foundation'),
    ('chathamhistoricdockyardtrust', 'Chatham Historic Dockyard Trust'),
    ('thecraftscouncil', 'The Crafts Council'),
    ('durhamwharffoundation', 'Durham Wharf Foundation'),
    ('friezefoundation', 'Frieze Foundation'),
    ("johnlyonscharity", "John Lyon's Charity"),
    ('mangroupplc', 'Man Group plc'),
    ('outsetfamily', "Outset Family"),
    ('therochesterbridgetrust', 'The Rochester Bridge Trust'),
    ('va', 'V&A'),
    ('wandsworthartsfestival', 'Wandsworth Arts Festival'),
)
