REACHOUT_PROJECT_CHOICES = (
    ('thebigdraw', 'The Big Draw'),
    ('creativequarter', 'Creative Quarter'),
    ('durhamwharfresidency', 'Durham Wharf Residency'),
    ('friezeartfair', 'Frieze Art Fair'),
    ('ignite', 'Ignite'),
    ('openspace', 'Open Space'),
    ('revival', 'Revival'),
    ('showrca', 'Show RCA'),
    ('teachersstudio', "Teachers' Studio"),
    ('workinprogressshow', 'Work-in-progress Show'),
)

REACHOUT_PARTICIPANTS_CHOICES = (
    ('alexandraandainsworthestate', 'Alexandra and Ainsworth Estate'),
    ('ashcrofttechnologyacademy', 'Ashcroft Technology Academy'),
    ('bournemouthpoolefecollege', 'Bournemouth & Poole FE College'),
    ('brentsidehighschool', 'Brentside High School'),
    ('burntwoodschool', 'Burntwood School'),
    ('cityoflondonschool', 'City of London School'),
    ('claptongirlsacademy', "Clapton Girls' Academy"),
    ('cumberlandschool', 'Cumberland School'),
    ('downtonlacemakers', "Downton lace-makers"),
    ('dunravenschool', 'Dunraven School'),
    ('ernestbevincollege', 'Ernest Bevin College'),
    ('families', 'Families'),
    ('fulhamcrossgirlsschool', "Fulham Cross Girls' School"),
    ('greycoathospitalschool', 'Grey Coat Hospital School'),
    ('haveringsixthformcollege', 'Havering Sixth Form College'),
    ('heathfieldschoolforgirls', 'Heathfield School for Girls'),
    ('henriettabarnettschool', "Henrietta Barnett School"),
    ('hollandparkschool', 'Holland Park School'),
    ('horizonscentre', "Horizons Centre"),
    ('kingsburyhighschool', 'Kingsbury High School'),
    ('parkviewacademy', 'Park View Academy'),
    ('queensparkcommunityschool', 'Queens Park Community School'),
    ('rcastudents', "RCA students"),
    ('refugeesandasylumseekers', 'Refugees and asylum seekers'),
    ('teachers', 'Teachers'),
    ('salisburymuseum', 'Salisbury Museum'),
    ('southwarkpensionerscentre', "Southwark Pensioners' Centre"),
    ('staugustinescofeschool', "St Augustine's C of E School"),
    ('stceciliasschool', "St Cecilia's School"),
    ('stjamescatholichighschool', "St James' Catholic High School"),
    ('stmaryleboneschoolcofeschool', "St Marylebone School C of E School"),
    ('stmichaelscatholicgrammarschool', "St Michael's Catholic Grammar School"),
    ('surreysquareprimaryschool', "Surrey Square Primary School"),
    ('thecomptonschool', "The Compton School"),
    ('villiershighschool', "Villiers High School"),
    ('youngcarers', "Young Carers"),
    ('westminsteracademy', "Westminster Academy"),
    ('whitefieldschool', "Whitefield School"),
    ('woolwichpolytechnicschool', "Woolwich Polytechnic School"),
)

REACHOUT_THEMES_CHOICES = (
    ('animation','Animation'),
    ('architecture','Architecture'),
    ('ceramicsglass','Ceramics \& Glass'),
    ('collaboration','Collaboration'),
    ('collage','Collage'),
    ('curating','Curating'),
    ('drawing','Drawing'),
    ('fashion','Fashion'),
    ('film','Film'),
    ('graphicdesign','Graphic Design'),
    ('jewellery','Jewellery'),
    ('illustration','Illustration'),
    ('information design','Information Design'),
    ('innovation','Innovation'),
    ('lifedrawing','Life Drawing'),
    ('painting','Painting'),
    ('performance','Performance'),
    ('photography','Photography'),
    ('printmaking','Printmaking'),
    ('productdesign','Product Design'),
    ('sculpture','Sculpture'),
    ('textiles','Textiles'),
    ('vehicledesign','Vehicle Design'),
    ('visualcommunication','Visual Communication'),
    ('writing','Writing'),
)

REACHOUT_PARTNERSHIPS_CHOICES = (
    ('allpartnerships', 'All partnerships'),
    ('artontheunderground', 'Art on the Underground'),
    ('creativequarter', 'Creative Quarter'),
    ('burberryfoundation', 'Burberry Foundation'),
    ('thecraftscouncil', 'The Crafts Council'),
    ('durhamwharffoundation', 'Durham Wharf Foundation'),
    ('friezefoundation', 'Frieze Foundation'),
    ("johnlyonscharity", "John Lyon's Charity"),
    ('mangroupplc', 'Man Group plc'),
    ('va', 'V&A'),
    ('wandsworthartsfestival', 'Wandsworth Arts Festival'),
)
